language: julia
os:
    - linux
    - osx
julia:
    - release
notifications:
    email: false
script:
    - julia --code-coverage test/runtests.jl
after_success:
    - julia -e 'Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
